# Site settings
title              : "Undergraduate Research and Arts Expo"
description        : ""
publisher          : "Northwestern University Libraries"
rights             : "All Rights Reserved"
license            : "None"
url                :
baseurl            :
encoding           : utf-8
google_analytics   : "UA-116823108-2"


# Editorial
editors:
  name             : "Office of Undergraduate Research"
  avatar           : ""
  bio              : "Integrating student learning with experiences in the world beyond the classroom"
  street_address   : "1801 Hinman Avenue"
  town_zip         : "Evanston, IL 60208"
  email            : "undergradresearch@northwestern.edu"
  phone            : "847-467-0499"
  uri              : "http://undergradresearch.northwestern.edu"
  home             :
  facebook         : "http://www.facebook.com/URatNU"
  github           : "nulib/undergrad-expo"
  twitter          :
  youtube          : "http://www.youtube.com/user/OURNU"

# Reading file
include:
exclude:
keep_files:
encoding: "utf-8"
markdown_ext: "md"

# Conversion
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  pages:
    output: true
    permalink: /:path/
  posters:
    output: true
    permalink: /:collection/:year/:title/
  presentations:
    output: true
    permalink: /:collection/:year/:title/

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posters"
    values:
      layout: "poster"
      format: "Poster"
      research: true
  -
    scope:
      path: ""
      type: "presentations"
    values:
      layout: "presentation"
      format: "Presentation"
      research: true
